# Writes OUT, a C++ source defining tmk::crules::builtin_catalogue_json(), from the catalogue JSON file IN.
# The JSON is ASCII (scripts/crules_catalogue.py), so it is split into raw-string chunks below the 65536-byte
# literal length ISO C++ guarantees (-Wpedantic warns above it) at any byte.
file(READ "${IN}" content)
string(LENGTH "${content}" len)
set(chunk 30000)
set(body "")
set(pos 0)
while(pos LESS len)
  string(SUBSTRING "${content}" ${pos} ${chunk} piece)
  string(APPEND body "    R\"tmkcat(${piece})tmkcat\",\n")
  math(EXPR pos "${pos} + ${chunk}")
endwhile()
file(WRITE "${OUT}" "// Generated by src/crules/embed.cmake from src/crules/catalogue.json. Do not edit.
#include <string>
#include <string_view>

namespace tmk::crules {

std::string_view builtin_catalogue_json() {
  static const char* const kChunks[] = {
${body}  };
  static const std::string kJson = [] {
    std::string s;
    for (const char* c : kChunks) s += c;
    return s;
  }();
  return kJson;
}

}  // namespace tmk::crules
")
